version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: digitalh-site
    restart: always
    ports:
      - "3015:3000"
    volumes:
      - ./database:/app/database
    environment:
      - NODE_ENV=production
      - PAYLOAD_SECRET=digitalh-super-secret-2026-xK9mR4pQ
